services:
  actuary_sjsu:
    build: .
    container_name: actuary
    ports:
      - '4040:4040'
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=4040
    restart: unless-stopped
